name: running the MQ commands

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: run MQ commands on QM3
      shell: bash
      run:  chmod 775 createlocal.sh
    - name: run the script
      shell: bash
      run: ./createlocal.sh
      
